service: aws-scheduling-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline
  - serverless-offline-plus-static

custom:
  localDevStaticFolder: path/to/static/files

functions:
  createSchedule:
    handler: src/handlers/scheduleHandler.create
    events:
      - http:
          path: schedule
          method: post
          cors: true
  getOneSchedule:
    handler: src/handlers/scheduleHandler.getOne
    events:
      - http:
          path: schedule/{id}
          method: get
          cors: true
  getAllSchedule:
    handler: src/handlers/scheduleHandler.getAll
    events:
      - http:
          path: schedule
          method: get
          cors: true
  updateSchedule:
    handler: src/handlers/scheduleHandler.update
    events:
      - http:
          path: schedule/{id}
          method: put
          cors: true
  deleteSchedule:
    handler: src/handlers/scheduleHandler.delete
    events:
      - http:
          path: schedule/{id}
          method: delete
          cors: true
  createRoom:
    handler: src/handlers/roomHandler.create
    events:
      - http:
          path: room
          method: post
          cors: true
  createScheduleRequest:
    handler: src/handlers/scheduleRequestHandler.create
    events:
      - http:
          path: schedulerequest
          method: post
          cors: true
