service: aws-scheduling-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline
  - serverless-offline-plus-static

custom:
  localDevStaticFolder: path/to/static/files

functions:
  getOneSchedule:
    handler: src/handlers/scheduleHandler.getOne
    events:
      - http:
          path: schedule/{id}
          method: get
          cors:
            origin: "*" # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
  getAllSchedule:
    handler: src/handlers/scheduleHandler.getAll
    events:
      - http:
          path: schedule
          method: get
          cors: false
  updateSchedule:
    handler: src/handlers/scheduleHandler.update
    events:
      - http:
          path: schedule/{id}
          method: put
          cors: true
  deleteSchedule:
    handler: src/handlers/scheduleHandler.delete
    events:
      - http:
          path: schedule/{id}
          method: delete
          cors: true
  createRoom:
    handler: src/handlers/roomHandler.create
    events:
      - http:
          path: room
          method: post
          cors: true
  createScheduleRequest:
    handler: src/handlers/scheduleRequestHandler.create
    events:
      - http:
          path: schedulerequest
          method: post
          cors: true
  confirmScheduleRequest:
    handler: src/handlers/scheduleHandler.confirmScheduleRequest
    events:
      - http:
          path: confirmschedulerequest/{id}
          method: get
          cors: true
  getAllProduct:
    handler: src/handlers/productHandler.getAll
    events:
      - http:
          path: product
          method: get
          cors: true
  createProduct:
    handler: src/handlers/productHandler.create
    events:
      - http:
          path: product
          method: post
          cors: true
  createSale:
    handler: src/handlers/saleHandler.create
    events:
      - http:
          path: sale
          method: post
          cors: true
